# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BLDC_design/BLDC_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLDC_design || ORIG_REF_NAME==BLDC_design}]

# IP: bd/BLDC_design/ip/BLDC_design_processing_system7_0_0/BLDC_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLDC_design_processing_system7_0_0 || ORIG_REF_NAME==BLDC_design_processing_system7_0_0}]

# IP: bd/BLDC_design/ip/BLDC_design_btn_counter_0_0/BLDC_design_btn_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLDC_design_btn_counter_0_0 || ORIG_REF_NAME==BLDC_design_btn_counter_0_0}]

# IP: bd/BLDC_design/ip/BLDC_design_debounce_0_0/BLDC_design_debounce_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLDC_design_debounce_0_0 || ORIG_REF_NAME==BLDC_design_debounce_0_0}]

# IP: bd/BLDC_design/ip/BLDC_design_debounce_0_1/BLDC_design_debounce_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BLDC_design_debounce_0_1 || ORIG_REF_NAME==BLDC_design_debounce_0_1}]

# XDC: bd/BLDC_design/BLDC_design_ooc.xdc
