# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jalop17/01-scripts/02-HDL/BLDC-motor-controller/BLDC-motor-controller.srcs/sources_1/bd/BLDC_design/ip/BLDC_design_processing_system7_0_0/BLDC_design_processing_system7_0_0.xci
# IP: The module: 'BLDC_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jalop17/01-scripts/02-HDL/BLDC-motor-controller/BLDC-motor-controller.srcs/sources_1/bd/BLDC_design/ip/BLDC_design_processing_system7_0_0/BLDC_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BLDC_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/jalop17/01-scripts/02-HDL/BLDC-motor-controller/BLDC-motor-controller.srcs/sources_1/bd/BLDC_design/ip/BLDC_design_processing_system7_0_0/BLDC_design_processing_system7_0_0.xci
# IP: The module: 'BLDC_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jalop17/01-scripts/02-HDL/BLDC-motor-controller/BLDC-motor-controller.srcs/sources_1/bd/BLDC_design/ip/BLDC_design_processing_system7_0_0/BLDC_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'BLDC_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
